apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: philipstpierre-com-tls
spec:
  secretName: philipstpierre-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: philipstpierre.com
  dnsNames:
    - philipstpierre.com
    - www.philipstpierre.com